server:
  port: 8085

spring:
  application:
    name: edusync-academics
  datasource:
    url: jdbc:postgresql://localhost:5432/edusync_erp
    username: edusync
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/edusync_erp

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
